In [53]:
import pandas as pd

In [100]:
df = pd.read_csv(r'C:\Users\b1090197\OneDrive\Documents\TexSense\Code\Study1\files\pi_og_idxs.csv', sep = ';')

In [101]:
#df['gct']=(df['w2']-df['w1'])/100

In [102]:
df['Participant'].unique()

array(['P07', 'P05', 'P04', 'P06', 'P01', 'P02'], dtype=object)

In [103]:
df['File']=df['Participant'] + '_' + df['Shoe'] + '_OG_' + df['OG'].astype(str)

In [105]:
df

    Participant Shoe  OG L/R   w1   w2         File
0           P07   UB   9   R  279  303  P07_UB_OG_9
1           P07   UB   8   R  410  434  P07_UB_OG_8
2           P07   UB   7   R  265  289  P07_UB_OG_7
3           P07   UB   6   R  423  447  P07_UB_OG_6
4           P07   UB   5   L  243  273  P07_UB_OG_5
..          ...  ...  ..  ..  ...  ...          ...
175         P02   UB   5   R  245  285  P02_UB_OG_5
176         P02   UB   6   L  302  344  P02_UB_OG_6
177         P02   UB   7   L  336  375  P02_UB_OG_7
178         P02   UB   8   L  266  302  P02_UB_OG_8
179         P02   UB   9   L  263  300  P02_UB_OG_9

[180 rows x 7 columns]

In [106]:
from pathlib import Path

In [122]:
p =Path('D:\Salzburg\Study1')/'P01'/('P01_OG')
sorted(p.glob('*.csv'))[0].name.split('_')[0]

'20221205'

In [137]:
df

    Participant Shoe  OG L/R   w1   w2         File      Date
0           P07   UB   9   R  279  303  P07_UB_OG_9  20230104
1           P07   UB   8   R  410  434  P07_UB_OG_8  20230104
2           P07   UB   7   R  265  289  P07_UB_OG_7  20230104
3           P07   UB   6   R  423  447  P07_UB_OG_6  20230104
4           P07   UB   5   L  243  273  P07_UB_OG_5  20230104
..          ...  ...  ..  ..  ...  ...          ...       ...
175         P02   UB   5   R  245  285  P02_UB_OG_5  20221207
176         P02   UB   6   L  302  344  P02_UB_OG_6  20221207
177         P02   UB   7   L  336  375  P02_UB_OG_7  20221207
178         P02   UB   8   L  266  302  P02_UB_OG_8  20221207
179         P02   UB   9   L  263  300  P02_UB_OG_9  20221207

[180 rows x 8 columns]

In [138]:
df['Date'] = None
for participant in df['Participant'].unique():
    p = Path('D:\Salzburg\Study1')/participant/(participant+'_OG')
    date = sorted(p.glob('*.csv'))[0].name.split('_')[0]
    df.loc[df['Participant']==participant, 'Date'] = date

In [155]:
df['path_nexus']=Path('D:/Salzburg/Study1/')/df['Participant']/(df['Participant']+'_OG')/(df['Date']+'_'+ df['File'] + '.csv')
df['path_pi']=Path('D:/Salzburg/Study1/')/df['Participant']/(df['Participant']+'_PI_df')/(df['File'] + '.csv')

In [157]:
df

,Participant,Shoe,OG,L/R,w1,w2,File,Date,path_nexus,path_pi
0,P07,UB,9,R,279,303,P07_UB_OG_9,20230104,D:\Salzburg\Study1\P07\P07_OG\20230104_P07_UB_...,D:\Salzburg\Study1\P07\P07_PI_df\P07_UB_OG_9.csv
1,P07,UB,8,R,410,434,P07_UB_OG_8,20230104,D:\Salzburg\Study1\P07\P07_OG\20230104_P07_UB_...,D:\Salzburg\Study1\P07\P07_PI_df\P07_UB_OG_8.csv
2,P07,UB,7,R,265,289,P07_UB_OG_7,20230104,D:\Salzburg\Study1\P07\P07_OG\20230104_P07_UB_...,D:\Salzburg\Study1\P07\P07_PI_df\P07_UB_OG_7.csv
3,P07,UB,6,R,423,447,P07_UB_OG_6,20230104,D:\Salzburg\Study1\P07\P07_OG\20230104_P07_UB_...,D:\Salzburg\Study1\P07\P07_PI_df\P07_UB_OG_6.csv
4,P07,UB,5,L,243,273,P07_UB_OG_5,20230104,D:\Salzburg\Study1\P07\P07_OG\20230104_P07_UB_...,D:\Salzburg\Study1\P07\P07_PI_df\P07_UB_OG_5.csv
...,...,...,...,...,...,...,...,...,...,...
175,P02,UB,5,R,245,285,P02_UB_OG_5,20221207,D:\Salzburg\Study1\P02\P02_OG\20221207_P02_UB_...,D:\Salzburg\Study1\P02\P02_PI_df\P02_UB_OG_5.csv
176,P02,UB,6,L,302,344,P02_UB_OG_6,20221207,D:\Salzburg\Study1\P02\P02_OG\20221207_P02_UB_...,D:\Salzburg\Study1\P02\P02_PI_df\P02_UB_OG_6.csv
177,P02,UB,7,L,336,375,P02_UB_OG_7,20221207,D:\Salzburg\Study1\P02\P02_OG\20221207_P02_UB_...,D:\Salzburg\Study1\P02\P02_PI_df\P02_UB_OG_7.csv
178,P02,UB,8,L,266,302,P02_UB_OG_8,20221207,D:\Salzburg\Study1\P02\P02_OG\20221207_P02_UB_...,D:\Salzburg\Study1\P02\P02_PI_df\P02_UB_OG_8.csv
179,P02,UB,9,L,263,300,P02_UB_OG_9,20221207,D:\Salzburg\Study1\P02\P02_OG\20221207_P02_UB_...,D:\Salzburg\Study1\P02\P02_PI_df\P02_UB_OG_9.csv

In [99]:
for child in (origin/'P01'/'P01_OG').iterdir():
    if str(child.name)[9:-4] in list(df['File']):
        print(str(child.name)[9:-4])

P01_RC_OG_2
P01_RC_OG_3
P01_RC_OG_4
P01_RC_OG_5
P01_RC_OG_6
P01_RC_OG_7
P01_RC_OG_8
P01_RC_OG_9
P01_RC_OG_10
P01_RC_OG_11
P01_RC_OG_2
P01_RC_OG_3
P01_RC_OG_4
P01_RC_OG_5
P01_RC_OG_6
P01_RC_OG_7
P01_RC_OG_8
P01_RC_OG_9
P01_RC_OG_10
P01_RC_OG_11
P01_RC_OG_2
P01_RC_OG_3
P01_RC_OG_4
P01_RC_OG_5
P01_RC_OG_6
P01_RC_OG_7
P01_RC_OG_8
P01_RC_OG_9
P01_RC_OG_10
P01_RC_OG_11
P01_BOS_OG_7
P01_BOS_OG_8
P01_BOS_OG_9
P01_BOS_OG_10
P01_BOS_OG_11
P01_BOS_OG_12
P01_BOS_OG_13
P01_BOS_OG_14
P01_BOS_OG_15
P01_BOS_OG_16
P01_BOS_OG_7
P01_BOS_OG_8
P01_BOS_OG_9
P01_BOS_OG_10
P01_BOS_OG_11
P01_BOS_OG_12
P01_BOS_OG_13
P01_BOS_OG_14
P01_BOS_OG_15
P01_BOS_OG_16
P01_BOS_OG_7
P01_BOS_OG_8
P01_BOS_OG_9
P01_BOS_OG_10
P01_BOS_OG_11
P01_BOS_OG_12
P01_BOS_OG_13
P01_BOS_OG_14
P01_BOS_OG_15
P01_BOS_OG_16
P01_UB_OG_2
P01_UB_OG_3
P01_UB_OG_4
P01_UB_OG_5
P01_UB_OG_6
P01_UB_OG_7
P01_UB_OG_8
P01_UB_OG_9
P01_UB_OG_10
P01_UB_OG_2
P01_UB_OG_3
P01_UB_OG_4
P01_UB_OG_5
P01_UB_OG_6
P01_UB_OG_7
P01_UB_OG_8
P01_UB_OG_9
P01_UB_OG_10
P01_UB_OG_2
P01_UB_OG_3
P01_UB_OG_4
P01_UB_OG_5
P01_UB_OG_6
P01_UB_OG_7
P01_UB_OG_8
P01_UB_OG_9
P01_UB_OG_10

In [87]:
li = []
for file in glob.glob(str(origin / 'P01'/ 'P01_OG')+'//*.csv'):
    print(file)

    if file[9:-4] in df['File']:
        print(file)

D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_static_2.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_1.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_2.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_3.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_4.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_5.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_6.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_7.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_8.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_9.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_10.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_RC_OG_11.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_static_3.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_1.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_2.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_3.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_4.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_5.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_6.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_7.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_8.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_9.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_10.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_11.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_12.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_13.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_14.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_15.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_OG_16.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_BOS_racalibrate_pelvis.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_static2.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_2.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_3.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_4.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_5.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_6.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_7.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_8.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_9.csv
D:\Salzburg\Study1\P01\P01_OG\20221205_P01_UB_OG_10.csv

In [69]:
for child in origin.iterdir():
    if child.is_dir():
        print(child)

D:\Salzburg\Study1\P01
D:\Salzburg\Study1\P02
D:\Salzburg\Study1\P03
D:\Salzburg\Study1\P05
D:\Salzburg\Study1\P04
D:\Salzburg\Study1\P06
D:\Salzburg\Study1\P07

In [70]:
import glob

In [74]:
glob.glob(str(origin)+'\\'+'*')

['D:\\Salzburg\\Study1\\P01',
 'D:\\Salzburg\\Study1\\hmdp.txt',
 'D:\\Salzburg\\Study1\\P02',
 'D:\\Salzburg\\Study1\\P03',
 'D:\\Salzburg\\Study1\\P05',
 'D:\\Salzburg\\Study1\\P04',
 'D:\\Salzburg\\Study1\\P06',
 'D:\\Salzburg\\Study1\\Participants.xlsx',
 'D:\\Salzburg\\Study1\\P07']